
server:
  port: 2022
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456